### PR TITLE
chore: add updated typization for DTR

### PR DESCRIPTION
**Pull request by arnoweiss**
## Description

This fixes a part of the asset-registration payloads. As the umbrella-helm-chart still uses tractusx-edc 0.5.x, the property `asset:prop:type` can't be removed yet as it's critical for catalog filtering. The whole chart appears to currently target R24-03.

Functionally, this doesn't change anything. Since the `dct:type` property however was already mandatory in R24-03, it should still be included and will become relevant for interoperability as soon as this chart target R24-05 with tractusx-edc 0.7.x.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by evegufy — COMMENTED** [review]
Hi @arnoweiss thank you the change, could you please rebase to main and bump the version of the tx-data-provider chart to 0.0.6?
Hi @ds-jhartmann could you please have a quick look at the change?

**Comment by arnoweiss** [comment]
Closing - I'll redo this when upgrading to EDC 0.7.0 since the payloads are gonna change again anyway.

**Comment by evegufy** [comment]
@arnoweiss just letting you know that changing to EDC 0.7.0 might not be feasible for quite a while due to the non-foss wallet situation with 24.05, so there might be some benefit in having a working dtr - edc communication at least in the state of 24.03

**Comment by arnoweiss** [comment]
y'all already have this - just using retro payloads. The 24-05 way of doing it isn't feasible with tractusx-edc 0.5.x because you can't write nested queryspec-filterexpressions on catalog-retrieval.

**Pull request closed without merging**
