### PR TITLE
feat: change edc-miw-keycloak-secret in tx-data-provider

### LINKED ISSUE #130: Change edc-miw-keycloak-secret in tx-data-provider
### Description

The name suggests that the secret / secret alias is the client secret in centralidp Keycloak when using the Managed Identity Wallet (MIW).

https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-1.0.0/charts/tx-data-provider/values.yaml#L36
https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-1.0.0/charts/tx-data-provider/templates/post-install-vault-setup.yaml#L58

This can be confusing because, since since R2405, MIW is no longer the wallet, see [note](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-1.0.0/charts/umbrella/README.md#note-for-r2405) for more information.

It should be renamed because we use it now with together with the [IATP mock](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-1.0.0/charts/umbrella/values.yaml#L642) and the [SSI DIM Wallet Stub](https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/122).

I suggest to rename it to `edc-wallet-secret`.

### PR DESCRIPTION
**Pull request by CDiezRodriguez**
## Description
Rename `edc-miw-keycloak-secret` to `edc-secret`.
Closes #130 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by mgarciaLKS** [comment]
Waiting for the #125 to be merged

**Review by evegufy — CHANGES_REQUESTED** [review]
Hi @CDiezRodriguez thank you, looks very good!
Now that I look at it, it might more explicit to call the new value `edc-wallet-secret`, could you please still change that?

**Comment by CDiezRodriguez** [comment]
> Hi @CDiezRodriguez thank you, looks very good! Now that I look at it, it might more explicit to call the new value `edc-wallet-secret`, could you please still change that?

Sure, @evegufy, I'll update the value to `edc-wallet-secret`

**Review by evegufy — APPROVED** [review]
Thank you @CDiezRodriguez

**Pull request merged**
