### PR TITLE
chore: switch to released data provider chart

### PR DESCRIPTION
**Pull request by ds-jhartmann**
## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by evegufy — CHANGES_REQUESTED** [review]
revert approval due to failed install

**Review by evegufy — CHANGES_REQUESTED** [review]
Hi @ds-jhartmann 

due to presumed issue that the umbrella chart was running out for resources during install, I reviewed the tx-data-provider integration more thoroughly.

I noticed that in its current setup, the values file from the tx-data-provider chart and - afterwards when integrated - the values file from the umbrella chart don't perform any kind of overwrite on the subcharts (tractusx-connector, digital-twin-registry, simple-data-backend and vault).
I assume the connection to the subcharts fails because most of them have hyphens in the chart name. I tried to work with aliases in tx-data-provider chart, and that works, so the overwrite from the values file from the tx-data-provider was taken into account but when integrating, the overwrite from the values file of the umbrella still doesn't work.

Note: once the overwrite from the values file from the tx-data-provider works, the dependency to the common chart of Bitnami of the digital-twin-registry causes issues with the postgres setup.

Let's discuss next week how to proceed. Maybe it's better to add the charts for the tx-data-provider directly to the umbrella chart and work with aliases for setting up some charts multiple times, in order to avoid such nested situations.

**Comment by evegufy** [comment]
> Hi @ds-jhartmann
> 
> due to presumed issue that the umbrella chart was running out of resources during install, I reviewed the tx-data-provider integration more thoroughly.
> 
> I noticed that in its current setup, the values file from the tx-data-provider chart and - afterwards when integrated - the values file from the umbrella chart don't perform any kind of overwrite on the subcharts (tractusx-connector, digital-twin-registry, simple-data-backend and vault). I assume the connection to the subcharts fails because most of them have hyphens in the chart name. I tried to work with aliases in tx-data-provider chart, and that works, so the overwrite from the values file from the tx-data-provider was taken into account but when integrating, the overwrite from the values file of the umbrella still doesn't work.
> 
> Note: once the overwrite from the values file from the tx-data-provider works, the dependency to the common chart of Bitnami of the digital-twin-registry causes issues with the postgres setup.
> 
> Let's discuss next week how to proceed. Maybe it's better to add the charts for the tx-data-provider directly to the umbrella chart and work with aliases for setting up some charts multiple times, in order to avoid such nested situations.

I did look into it a bit more:

Some corrections: 
- the values file from the tx-data-provider chart does perform the expected overwrite when installing the tx-data-provider directly
-  the values file from the umbrella chart does perform the expected overwrite if only one, dataconsumer or dataprovider, is enabled (even though dataprovider did run into the following error if the password for the dtr database was not set `Error: INSTALLATION FAILED: template: umbrella/charts/dataprovider/charts/digital-twin-registry/templates/registry/postgres-init.yaml:35:63: executing "umbrella/charts/dataprovider/charts/digital-twin-registry/templates/registry/postgres-init.yaml" at <b64enc>: invalid value; expected string`)
-  the digital-twin-registry chart doesn't have a direct dependency to the common chart of bitnami

There were to issues at play (all solved there https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/73):
- dataconsumer and dataprovider couldn't be enabled at the same time without running into an related to the existingSecret override in the digital-twin-registry chart, I changed to a working setup https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/73/commits/9376e25551982fb3442a381e9cbb8fe56b9c31a4
- the install of the umbrella chart was running out of resources with the tx-data-provider components integrated and enabled: due to that I reworked the chart testing concept: https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/73

I recommend to close this PR and merge https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/73 instead.

**Comment by ds-jhartmann** [comment]
> > Hi @ds-jhartmann
> > due to presumed issue that the umbrella chart was running out of resources during install, I reviewed the tx-data-provider integration more thoroughly.
> > I noticed that in its current setup, the values file from the tx-data-provider chart and - afterwards when integrated - the values file from the umbrella chart don't perform any kind of overwrite on the subcharts (tractusx-connector, digital-twin-registry, simple-data-backend and vault). I assume the connection to the subcharts fails because most of them have hyphens in the chart name. I tried to work with aliases in tx-data-provider chart, and that works, so the overwrite from the values file from the tx-data-provider was taken into account but when integrating, the overwrite from the values file of the umbrella still doesn't work.
> > Note: once the overwrite from the values file from the tx-data-provider works, the dependency to the common chart of Bitnami of the digital-twin-registry causes issues with the postgres setup.
> > Let's discuss next week how to proceed. Maybe it's better to add the charts for the tx-data-provider directly to the umbrella chart and work with aliases for setting up some charts multiple times, in order to avoid such nested situations.
> 
> I did look into it a bit more:
> 
> Some corrections:
> 
> * the values file from the tx-data-provider chart does perform the expected overwrite when installing the tx-data-provider directly
> * the values file from the umbrella chart does perform the expected overwrite if only one, dataconsumer or dataprovider, is enabled (even though dataprovider did run into the following error if the password for the dtr database was not set `Error: INSTALLATION FAILED: template: umbrella/charts/dataprovider/charts/digital-twin-registry/templates/registry/postgres-init.yaml:35:63: executing "umbrella/charts/dataprovider/charts/digital-twin-registry/templates/registry/postgres-init.yaml" at <b64enc>: invalid value; expected string`)
> * the digital-twin-registry chart doesn't have a direct dependency to the common chart of bitnami
> 
> There were to issues at play (all solved here #73):
> 
> * dataconsumer and dataprovider couldn't be enabled at the same time without running into an error related to the existingSecret override in the digital-twin-registry chart, I changed to a working setup [9376e25](https://github.com/eclipse-tractusx/tractus-x-umbrella/commit/9376e25551982fb3442a381e9cbb8fe56b9c31a4)
> * the install of the umbrella chart was running out of resources with the tx-data-provider components integrated and enabled: due to that I reworked the chart testing concept: [chore: rework chart testing and tx-data-provider #73](https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/73)
> 
> I recommend to close this PR and merge #73 instead.

Thanks a lot for the feedback and fixes.
Closing this PR since it will be fixed with https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/73

**Pull request closed without merging**
