### PR TITLE
feat: upgrade EDC to 0.7.7

### PR DESCRIPTION
**Pull request by kss682**
## Description

Upgrade EDC to 0.7.7  #134 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by evegufy — CHANGES_REQUESTED** [review]
Hi @kss682 thank you for you contribution, could you please direct the PR to main and rebase to main?
we need to test this change against the latest in changes in main (i.e. the integration of the SSI DIM Wallet Stub).

**Review by CDiezRodriguez — COMMENTED** [review]
If you upgrade the EDC version from 0.7.1 to 0.7.3, the query format may change. You'll need to update the tests to be compatible with version 0.7.3. The tests are located in the [resources](https://github.com/eclipse-tractusx/tractus-x-umbrella/tree/main/charts/tx-data-provider/resources) folder.

**Comment by mgarciaLKS** [comment]
Also tested it locally and works correctly.

**Review by mgarciaLKS — APPROVED** [review]

**Review by matbmoser — APPROVED** [review]
approved

**Review by evegufy — APPROVED** [review]
awesome that it's working now!
I'd merge once 2.0.5 from @tunacicek is merged https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/160

**Pull request merged**
