### PR TITLE
[DTR] Upgrade to R24.08

### PR DESCRIPTION
**Pull request by tunacicek**
## Description
Update dtr to 0.5.2

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by evegufy — CHANGES_REQUESTED** [review]
Hi @tunacicek IMO is makes sense that you redirect this PR to main to integrate with the latest developments. There is no need for a release branch because the switch from 24.05 (currently in main) to 24.08 should not be breaking.
Would have already made sense for https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/148 as well.
And just in case you missed it because the PR was already merged: I left a comment https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/148#discussion_r1831485288

**Comment by evegufy** [comment]
@tunacicek https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/149/commits/ac07437cfdd5759d01d08f261f1bcdd605841a72 for the biggest appears not be your commit

**Comment by evegufy** [comment]
@tunacicek could you please resolve the conflicts?

**Comment by evegufy** [comment]
@kss682 @CDiezRodriguez @mgarciaLKS could you someone test if the data exchange tutorial is still working after upgrading the DTR?
Don't forget to perform `helm dependency update ../tx-data-provider` and then `helm dependency update` before testing the change: [use-local-repository](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/main/charts/umbrella/README.md#use-local-repository)

**Review by CDiezRodriguez — APPROVED** [review]
Successfully tested data exchange

**Review by mgarciaLKS — APPROVED** [review]
Tested locally and worked well for me.

**Review by evegufy — APPROVED** [review]

**Pull request merged**
