### PR TITLE
feat: update SSI-DIM-Wallet-Stub to 0.1.4

### PR DESCRIPTION
**Pull request by CDiezRodriguez**
## Description

Update the SSI-DIM-Wallet-Stub version to 0.1.4 #169
Enhances Wallet Stub with BDRS function https://github.com/eclipse-tractusx/ssi-dim-wallet-stub/issues/29

The problem with this PR is that I tested the onboarding and data exchange. For me, the data exchange doesn’t work because the `dataprovider-controlplane` fails. It only works correctly if I restart the `dataprovider-controlplane`.

image

Edit: This issue has now been resolved.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by CDiezRodriguez** [comment]
If you leave 15-20 minutes and start process again (From Catalog Request), then It works fine.

**Comment by CDiezRodriguez** [comment]
I tried to increase the resources allocated to the SSI-DIM-Wallet-Stub, as the new functionality might require more resources. However, it didn’t work, and the problem persists.
```yaml
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1500m
        memory: 2Gi
```

**Comment by CDiezRodriguez** [comment]
I’m not sure why, but the first time the connector attempts to resolve the BDRs via the SSI-DIM-Wallet-Stub, it doesn’t work. According to the [connector configuration](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/charts/tractusx-connector/values.yaml#L162), it waits 600 seconds before retrying the resolution action. To address this issue, one option from the Umbrella chapter is to reduce the `cache_validity_seconds` value to 60. I'm not sure if this is valid. 

I’m not sure if this is a valid fix.

**Comment by nitin-vavdiya** [comment]
> @nitin-vavdiya could you please support @CDiezRodriguez here? Thank you!

Issue is resolved now, We added code to set up the wallet with seeding data.

**Review by nitin-vavdiya — APPROVED** [review]
LGTM!

**Review by mgarciaLKS — APPROVED** [review]
Tested and works fine 😃

**Comment by nitin-vavdiya** [comment]
@evegufy Should we merge this PR now, or should we wait until after the Community Days?

**Review by evegufy — CHANGES_REQUESTED** [review]
great that it works!
could you please also update the list of [involved components](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/43b9555701aa000bcb2045465062bbc3afb022e3/charts/umbrella/README.md?plain=1#L487)? SSI Credential issuer should also be removed, as it isn't enabled as well.

**Comment by nitin-vavdiya** [comment]
> great that it works! could you please also update the list of [involved components](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/43b9555701aa000bcb2045465062bbc3afb022e3/charts/umbrella/README.md?plain=1#L487)? SSI Credential issuer should also be removed, as it isn't enabled as well.

No, we only added BDRS directory API. Only BDRS will be removed

**Comment by CDiezRodriguez** [comment]
> > great that it works! could you please also update the list of [involved components](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/43b9555701aa000bcb2045465062bbc3afb022e3/charts/umbrella/README.md?plain=1#L487)? SSI Credential issuer should also be removed, as it isn't enabled as well.
> 
> No, we only added BDRS directory API. Only BDRS will be removed

We don't use SSI Credential Issuer in Data-Exchange, so it can be removed from the list.

**Review by evegufy — APPROVED** [review]

**Review by matbmoser — APPROVED** [review]
merge merge merge

**Pull request merged**
